name = "argv"
version = "1.1.0"
description = "A cross platform library for getting the command line arguments"
licences = ["Apache-2.0"]
repository = { type = "github", user = "dusty-phillips", repo = "macabre_argv" }

[dependencies]
gleam_stdlib = { git = "git@github.com:dusty-phillips/macabre_stdlib.git", ref = "main" }

[dev-dependencies]
gleeunit = { git = "git@github.com:dusty-phillips/macabre_gleeunit.git", ref = "main" }
